name: post new notices

on:
  workflow_dispatch:
  schedule:
    - cron: '10 * * * *'
jobs:
  Send_Note:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Python Install
        run: |
          python -m pip install --upgrade pip
          pip install Misskey.py
          pip install feedparser
          pip install atproto

      - name: Create Note
        env:
          MISSKEY_SERVER_ADDRESS: ${{ secrets.MISSKEY_SERVER_ADDRESS }}
          MISSKEY_TOKEN: ${{ secrets.MISSKEY_TOKEN }}
          NICONICO_USER_ID: ${{ secrets.NICONICO_USER_ID }}

        run: |
          python main.py
          cat date.txt

      - name: Update File
        run: |
          if ! git diff --exit-code --quiet
          then
           git add --update
            git config --global user.name ${{ secrets.YOUSER_NAME }}
            git config --global user.email ${{ secrets.MAIL_ADDRESS }}
            git commit -m "Update Content"
            git push
          fi
